
# This file was generated by the SOM Compiler.
# FileName: drgagent.psc.
# Generated using:
#     SOM Precompiler spc: 1.22
#     SOM Emitter emitpsc: 1.10

/*
 * Include the .sc file
 */
#include "DrgAgent.sc"

class: DrgAgent;

