
/*
 * This file was generated by the SOM Compiler.
 * FileName: drgagent.ph.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitph: 1.10
 */

#ifndef DrgAgent_ph
#define DrgAgent_ph


#include "DrgAgent.h"

/*
 * Include any needed private header files
 */

#endif       /* DrgAgent_ph */

/*
 * This file was generated by the SOM Compiler.
 * FileName: drgagent.ph.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitph: 1.10
 */

#ifndef DrgAgent_mph
#define DrgAgent_mph


/*
 * Include any needed private header files
 */

#endif       /* DrgAgent_ph */
