
# This file was generated by the SOM Compiler.
# FileName: drgagent.sc.
# Generated using:
#     SOM Precompiler spc: 1.22
#     SOM Emitter emitcsc: 1.10
#include "wpabs.sc"

class: DrgAgent, 
    file stem = DrgAgent, external prefix = Agent_, class prefix = AgentCls_, 
    major version = 1, minor version = 1, local;


parent class: WPAbstract;

methods:


    override wpDraggedOverObject, public, external;

    -- From WPObject

    override wpDroppedOnObject, public, external;

    -- From WPObject

    override wpclsQueryIconData, public, class, external;

    -- From WPObject

    override wpclsQueryStyle, public, class, external;

    -- From WPObject

    override wpclsQueryTitle, public, class, external;

    -- From WPObject

    override wpclsInitData, public, class, external;

    -- From WPObject

    override wpclsUnInitData, public, class, external;

    -- From WPObject

